In [1]:
import sys
import numpy as np
sys.path.append("../")

import XRayCrystalDatabase
from XRayCrystalDatabase import PropertyCalculator
from XRayCrystalDatabase.Database import xserver_benchmark_result

# Silicon Crystal

In [2]:
silicon_info = xserver_benchmark_result.silicon_info
silicon_benchmark =  xserver_benchmark_result.silicon

# Get energy list to investigate:
energy_list = list(silicon_info.keys())
print("For silicon, the following energies will be investigated:")
print(energy_list)
print("===========================================================")

# Loop through the energy
for energy in energy_list:
    
    # Get the numerical value of the energy
    energy_val = silicon_info[energy][0]
    
    # Get the index list to investigate
    index_list = silicon_info[energy][1:]
    
    # Loop through the miller index
    for miller in index_list:
        
        idx_val = miller[0]
        idx_text = miller[1]
        
        print("For energy:", energy)
        print("Miller index:", idx_text)
        
        ###################################################
        # Get the benchmark value
        chi0_benchmark = silicon_benchmark[energy][idx_text]['chi0']
        chih_sigma_benchmark = silicon_benchmark[energy][idx_text]['chih sigma']
        chih_pi_benchmark = silicon_benchmark[energy][idx_text]['chih pi']
        
        ###################################################
        # Get my own calculted value
        
        # Get the crystal
        my_crystal = PropertyCalculator.Silicon()

        # Get the 
        (chi0,
         chih_sigma,
         chih_pi,
         sanity) = PropertyCalculator.get_chi0_and_chih(crystal_type = my_crystal ,
                                                         xray_energy_kev = energy_val,
                                                         miller_idx = idx_val, 
                                                         temp=300.)
        
        difference = np.array([np.abs(chi0.real) - np.abs(chi0_benchmark.real),
                               np.abs(chi0.imag) - np.abs(chi0_benchmark.imag),
                               np.abs(chih_sigma.real) - np.abs(chih_sigma_benchmark.real),
                               np.abs(chih_sigma.imag) - np.abs(chih_sigma_benchmark.imag),
                               np.abs(chih_pi.real) - np.abs(chih_pi_benchmark.real),
                               np.abs(chih_pi.imag) - np.abs(chih_pi_benchmark.imag)])
        
        relative_difference = np.abs(np.array([chi0_benchmark.real,
                                               chi0_benchmark.imag,
                                               chih_sigma_benchmark.real,
                                               chih_sigma_benchmark.imag,
                                               chih_pi_benchmark.real,
                                               chih_pi_benchmark.imag])
                                    )
        
        relative_difference = difference / relative_difference
        
        with np.printoptions(precision=2, suppress=True):
            print(relative_difference)
        print("===================================================")

For silicon, the following energies will be investigated:
['8keV', '9keV', '10keV', '11keV']
For energy: 8keV
Miller index: 1,1,1
The atomic layer distance is 3.14 A.
[ 0.    0.   -0.03 -0.02 -0.03 -0.02]
For energy: 8keV
Miller index: 2,2,0
The atomic layer distance is 1.92 A.
[ 0.    0.   -0.07 -0.07 -0.07 -0.06]
For energy: 8keV
Miller index: 3,3,3
The atomic layer distance is 1.05 A.
[ 0.    0.   -0.23 -0.22 -0.23 -0.34]
For energy: 8keV
Miller index: 4,4,0
The atomic layer distance is 0.96 A.
[ 0.    0.   -0.27 -0.26 -0.27 -0.29]
For energy: 9keV
Miller index: 1,1,1
The atomic layer distance is 3.14 A.
[ 0.    0.   -0.03 -0.02 -0.03 -0.02]
For energy: 9keV
Miller index: 2,2,0
The atomic layer distance is 1.92 A.
[ 0.    0.   -0.07 -0.07 -0.07 -0.06]
For energy: 9keV
Miller index: 3,3,3
The atomic layer distance is 1.05 A.
[ 0.    0.   -0.23 -0.22 -0.23 -0.33]
For energy: 9keV
Miller index: 4,4,0
The atomic layer distance is 0.96 A.
[ 0.    0.   -0.27 -0.25 -0.27 -0.58]
For energy:

# Diamond

In [3]:
diamond_info = xserver_benchmark_result.diamond_info
diamond_benchmark =  xserver_benchmark_result.diamond

# Get energy list to investigate:
energy_list = list(silicon_info.keys())
print("For silicon, the following energies will be investigated:")
print(energy_list)
print("===========================================================")

# Loop through the energy
for energy in energy_list:
    
    # Get the numerical value of the energy
    energy_val = diamond_info[energy][0]
    
    # Get the index list to investigate
    index_list = diamond_info[energy][1:]
    
    # Loop through the miller index
    for miller in index_list:
        
        idx_val = miller[0]
        idx_text = miller[1]
        
        print("For energy:", energy)
        print("Miller index:", idx_text)
        
        ###################################################
        # Get the benchmark value
        chi0_benchmark = diamond_benchmark[energy][idx_text]['chi0']
        chih_sigma_benchmark = diamond_benchmark[energy][idx_text]['chih sigma']
        chih_pi_benchmark = diamond_benchmark[energy][idx_text]['chih pi']
        
        ###################################################
        # Get my own calculted value
        
        # Get the crystal
        my_crystal = PropertyCalculator.Diamond()

        # Get the 
        (chi0,
         chih_sigma,
         chih_pi,
         sanity) = PropertyCalculator.get_chi0_and_chih(crystal_type = my_crystal ,
                                                         xray_energy_kev = energy_val,
                                                         miller_idx = idx_val, 
                                                         temp=300.)
        
        difference = np.array([np.abs(chi0.real) - np.abs(chi0_benchmark.real),
                               np.abs(chi0.imag) - np.abs(chi0_benchmark.imag),
                               np.abs(chih_sigma.real) - np.abs(chih_sigma_benchmark.real),
                               np.abs(chih_sigma.imag) - np.abs(chih_sigma_benchmark.imag),
                               np.abs(chih_pi.real) - np.abs(chih_pi_benchmark.real),
                               np.abs(chih_pi.imag) - np.abs(chih_pi_benchmark.imag)])
        
        relative_difference = np.abs(np.array([chi0_benchmark.real,
                                               chi0_benchmark.imag,
                                               chih_sigma_benchmark.real,
                                               chih_sigma_benchmark.imag,
                                               chih_pi_benchmark.real,
                                               chih_pi_benchmark.imag])
                                    )
        
        relative_difference = difference / relative_difference
        
        with np.printoptions(precision=2, suppress=True):
            print(relative_difference)
        print("===================================================")

For silicon, the following energies will be investigated:
['8keV', '9keV', '10keV', '11keV']
For energy: 8keV
Miller index: 1,1,1
The atomic layer distance is 2.06 A.
[-0.    0.11 -0.08  0.05 -0.08  0.07]
For energy: 8keV
Miller index: 2,2,0
The atomic layer distance is 1.26 A.
[-0.    0.11 -0.15 -0.03 -0.15 -0.1 ]
For energy: 9keV
Miller index: 1,1,1
The atomic layer distance is 2.06 A.
[-0.    0.11 -0.08  0.06 -0.08  0.07]
For energy: 9keV
Miller index: 2,2,0
The atomic layer distance is 1.26 A.
[-0.    0.11 -0.15 -0.03 -0.15 -0.06]
For energy: 10keV
Miller index: 1,1,1
The atomic layer distance is 2.06 A.
[ 0.    0.1  -0.08  0.05 -0.08  0.06]
For energy: 10keV
Miller index: 2,2,0
The atomic layer distance is 1.26 A.
[ 0.    0.1  -0.14 -0.04 -0.14 -0.05]
For energy: 10keV
Miller index: 3,3,3
The atomic layer distance is 0.69 A.
[ 0.    0.1  -0.4  -0.34 -0.4  -0.33]
For energy: 10keV
Miller index: 4,4,0
The atomic layer distance is 0.63 A.
[ 0.    0.1  -0.46 -0.4  -0.46 -0.4 ]
For ene

# Germinium

In [5]:
germanium_info = xserver_benchmark_result.germanium_info
germanium_benchmark =  xserver_benchmark_result.germanium

# Get energy list to investigate:
energy_list = list(silicon_info.keys())
print("For silicon, the following energies will be investigated:")
print(energy_list)
print("===========================================================")

# Loop through the energy
for energy in energy_list:
    
    # Get the numerical value of the energy
    energy_val = germanium_info[energy][0]
    
    # Get the index list to investigate
    index_list = germanium_info[energy][1:]
    
    # Loop through the miller index
    for miller in index_list:
        
        idx_val = miller[0]
        idx_text = miller[1]
        
        print("For energy:", energy)
        print("Miller index:", idx_text)
        
        ###################################################
        # Get the benchmark value
        chi0_benchmark = germanium_benchmark[energy][idx_text]['chi0']
        chih_sigma_benchmark = germanium_benchmark[energy][idx_text]['chih sigma']
        chih_pi_benchmark = germanium_benchmark[energy][idx_text]['chih pi']
        
        ###################################################
        # Get my own calculted value
        
        # Get the crystal
        my_crystal = PropertyCalculator.Germanium()

        # Get the 
        (chi0,
         chih_sigma,
         chih_pi,
         sanity) = PropertyCalculator.get_chi0_and_chih(crystal_type = my_crystal ,
                                                         xray_energy_kev = energy_val,
                                                         miller_idx = idx_val, 
                                                         temp=300.)
        
        difference = np.array([np.abs(chi0.real) - np.abs(chi0_benchmark.real),
                               np.abs(chi0.imag) - np.abs(chi0_benchmark.imag),
                               np.abs(chih_sigma.real) - np.abs(chih_sigma_benchmark.real),
                               np.abs(chih_sigma.imag) - np.abs(chih_sigma_benchmark.imag),
                               np.abs(chih_pi.real) - np.abs(chih_pi_benchmark.real),
                               np.abs(chih_pi.imag) - np.abs(chih_pi_benchmark.imag)])
        
        relative_difference = np.abs(np.array([chi0_benchmark.real,
                                               chi0_benchmark.imag,
                                               chih_sigma_benchmark.real,
                                               chih_sigma_benchmark.imag,
                                               chih_pi_benchmark.real,
                                               chih_pi_benchmark.imag])
                                    )
        
        relative_difference = difference / relative_difference
        
        with np.printoptions(precision=2, suppress=True):
            print(relative_difference)
        print("===================================================")

For silicon, the following energies will be investigated:
['8keV', '9keV', '10keV', '11keV']
For energy: 8keV
Miller index: 1,1,1
The atomic layer distance is 3.27 A.
[ 0.01  0.01 -0.    0.   -0.    0.01]
For energy: 8keV
Miller index: 2,2,0
The atomic layer distance is 2.00 A.
[ 0.01  0.01 -0.02 -0.02 -0.02 -0.  ]
For energy: 9keV
Miller index: 1,1,1
The atomic layer distance is 3.27 A.
[ 0.01  0.03 -0.    0.02 -0.    0.02]
For energy: 9keV
Miller index: 2,2,0
The atomic layer distance is 2.00 A.
[ 0.01  0.03 -0.02 -0.   -0.02  0.01]
For energy: 10keV
Miller index: 1,1,1
The atomic layer distance is 3.27 A.
[ 0.01  0.02 -0.01  0.01 -0.01  0.01]
For energy: 10keV
Miller index: 2,2,0
The atomic layer distance is 2.00 A.
[ 0.01  0.02 -0.02 -0.01 -0.02  0.  ]
For energy: 10keV
Miller index: 3,3,3
The atomic layer distance is 1.09 A.
[ 0.01  0.02 -0.1  -0.07 -0.1  -0.11]
For energy: 10keV
Miller index: 4,4,0
The atomic layer distance is 1.00 A.
[ 0.01  0.02 -0.11 -0.09 -0.11 -0.17]
For ene